codecov:
  branch: main
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,files,footer
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
