name: Tests CI

on: [push, pull_request]

jobs:
  test-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test using Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run the tests
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
